ame: kitchain-ai
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - streamlit
      - pandas
      - joblib==1.5.1
      - scikit-learn==1.1.3
      - numpy==1.24.4
      - scipy==1.10.1
      - openpyxl
      - xgboost
